apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "ashkube"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "ashkube"
    spec:
      containers:
        - name: "ashkube"
          image: "ashcontainerregistry.azurecr.io/ashkube"
          ports:
          - containerPort: 80